language: ruby
rvm:
- 2.2

install: gem install jekyll html-proofer jekyll-sitemap
script: scripts/cibuild

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /(.*)-site/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  skip_cleanup: true
  provider: script
  script: scripts/deploy.sh
  on:
    branch: gh-pages
