language: ruby

script: script/cibuild

# branch whitelist
branches:
  only:
  - gh-pages     # test the gh-pages branch
  - /(.*)-site/ # test every branch which starts with "pages-"

env:
  global:
  - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer

deploy:
  skip_cleanup: true
  provider: script
  script: script/deploy
  on:
    branch: gh-pages

sudo: false # route your build to the container-based infrastructure for a faster build
